name: by JN
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#2a6b00'
    - '#a8a8a6'
    - '#b69000'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
